### ISSUE TITLE
Tile Service: Add

### ISSUE THREAD

**Issue by fenxe** [Caceresenzo/modern-rotation-control#1]
This is exactly an app I was looking for! It works perfectly for my android 14 device. Well, not exactly an issue but rather a suggestion.
1. Will you be adding a tile service (like one click to launch the app -- just to start that cool arranged notification / or configured to launch into the app's main activity screen whichever is fine (: ..
2. I know the app is intended for your personal usage, but I'm pretty sure many will find it useful so I think there should be release for non-debug app so the size should be much smaller (?)

**Comment by Caceresenzo** [comment]
Hi, I was not expecting a feature request :)

1. I was planning to add one at some point, but I need more research. I would like to have an inline menu like the flashlight one to avoid having to open a submenu.
2. This would require me to sign it, which I find "dangerous" because I might lose the key. 20mb is not that much compared to other applications these days. I also just use a lot of Google's library to simplify development, which makes it heavier.

If more people are interested, maybe I should release it on the PlayStore. That way there should be no "application appears over other applications" warning and updates would be easier for you.
I just do not want the original author to feel threatened by this application in any way.

If you really need a smaller application, please consider using the [Crape Myrtle's application](https://play.google.com/store/apps/details?id=org.crape.rotationcontrol&hl=en&pli=1).

**Comment by Caceresenzo** [comment]
A tile is available in the [v1.3](https://github.com/Caceresenzo/modern-rotation-control/releases/tag/1.3.0). Please don't hesitate to give me feedback!

I will add an option to disable the notification soon. But for now, you can just hide it using Android's notification category system.

**Comment by fenxe** [comment]
Thanks so much! It works great. Didn't expect this update, awesome.

**Comment by Caceresenzo** [comment]
After testing it myself, I found out that the Youtube app does not like it very much.
If you are actively watching a video, using the tile to change the orientation will make Youtube think you have switched apps and either stop the video or go into PiP.

I don't think there's much I can do about that...

**Comment by fenxe** [comment]
Oh, I used browser to access YouTube videos so I have no idea about that, I'll keep the issues open

**Comment by Caceresenzo** [comment]
I added an option to hide the notification in the [1.4](https://github.com/Caceresenzo/modern-rotation-control/releases/tag/1.4.0) release.

Unfortunately, I haven't been able to fix the problem with Youtube.
However, other players like VLC are not affected.

**Comment by Caceresenzo** [comment]
Hey @fenxe,

[I finally took the time to publish the application on the Play Store.](https://play.google.com/store/apps/details?id=dev.caceresenzo.rotationcontrol&pli=1)
